---
- name: Get VirtualBox version.
  shell: cat /root/.vbox_version
  register: virtualbox_version

- name: Mount VirtualBox guest additions ISO.
  mount: >
    name=/tmp/vbox
    src=/root/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso
    opts=loop
    state=mounted
    fstype=iso9660

- name: Run VirtualBox guest additions installation.
  shell: /tmp/vbox/VBoxLinuxAdditions.run --nox11 -- --force
  failed_when: false

- name: Unmount VirtualBox guest additions ISO.
  mount: >
    name=/tmp/vbox
    src=/root/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso
    state=absent
    fstype=iso9660

- name: Remove all ISOs in vagrant home directory.
  shell: "rm /root/*.iso"
