gitlab:
  image: gitlab/gitlab-ce
  ports:
    - "10080:80"
    - "10022:22"
  volumes:
    - /home/vagrant/docker/gitlab/data:/var/opt/gitlab
    - /home/vagrant/docker/gitlab/etc:/etc/gitlab
    - /home/vagrant/docker/gitlab/logs:/var/log/gitlab
