# let's do some docker
- name: docker
  hosts: all
  sudo: no
  vars:
    working_dir: /home/vagrant/docker
  tasks:
    - name: "vagrant docker data directory"
      file: path="{{ working_dir }}" state=directory

    - name: "upload docker compose"
      copy:
        src: ../docker-compose.yml
        dest: "{{ working_dir }}/docker-compose.yml"

    - name: "run docker compose"
      shell: chdir="{{ working_dir }}" /usr/bin/docker-compose up -d
      environment:
        COMPOSE_PROJECT_NAME: "ansible"
