# let's do some docker
- name: docker
  hosts: all
  sudo: no
  tasks:
    - name: "vagrant docker data directory"
      file: path="{{ item }}" state=directory
      with_items:
        - "/home/vagrant/docker"

    - name: "mktemp for docker-compose file"
      shell: /usr/bin/mktemp
      register: mktemp
      notify: mktemp remove

    - name: "upload docker compose"
      copy:
        src: ../docker-compose.yml
        dest: "{{ mktemp.stdout }}"

    - name: "run docker compose"
      shell: /usr/bin/docker-compose up -d
      environment:
        COMPOSE_FILE: "{{ mktemp.stdout }}"
        COMPOSE_PROJECT_NAME: "ansible"

  handlers:
    - name: mktemp remove
      file: path="{{ mktemp.stdout }}" state=absent
