---
- name: initial provision
  hosts: all
  sudo: yes
  tasks:
    - name: "yum update"
      yum: name=* state=latest

    - name: "yum install packages"
      yum: name="{{ item }}" state=present
      with_items:
        - ntp
        - acpid
        - docker
        - python-pip

    # state=latest is necessary here otherwise there are issues using the
    # docker-py module
    - name: pip install dependencies
      pip: name="docker-py" state=latest

    - name: "docker daemon options"
      lineinfile: >
        dest=/etc/sysconfig/docker
        line="OPTIONS='--selinux-enabled -G vagrant'"
        state=present
        regexp="^OPTIONS="

    - name: "set timezone UTC"
      command: /usr/bin/timedatectl set-timezone UTC

    - name: "enable services"
      service: name="{{ item }}" state=running enabled=yes
      with_items:
        - ntpd
        - acpid
        - docker

    - name: "timedatectl use ntp"
      command: /usr/bin/timedatectl set-ntp true
