---
- hosts: all
  sudo: yes
  tasks:
    - name: "yum update"
      yum: name=* state=latest

    - name: "yum install packages"
      yum: name="{{ item }}" state=present
      with_items:
        - ntp
        - acpid
        - docker
        - python-pip

    # state=latest is necessary here otherwise there are issues using the
    # docker-py module
    - name: pip install dependencies
      pip: name="docker-py" state=latest

    - name: "add vagrant to docker group"
      user: >
        name=vagrant
        append=yes
        groups=dockerroot
        state=present

    - name: "docker daemon options"
      lineinfile: >
        dest=/etc/sysconfig/docker
        line="OPTIONS='--selinux-enabled -G dockerroot'"
        state=present
        regexp="^OPTIONS="

    - name: "set timezone UTC"
      command: /usr/bin/timedatectl set-timezone UTC

    - name: "enable services"
      service: name="{{ item }}" state=running enabled=yes
      with_items:
        - ntpd
        - acpid
        - docker

    - name: "timedatectl use ntp"
      command: /usr/bin/timedatectl set-ntp true


# let's do some docker
- hosts: all
  sudo: yes
  sudo_user: vagrant
  vars:
      postgres_password: rW41gWckkcR9Uer1
  tasks:
    - name: "vagrant docker data directory"
      file: path="{{ item }}" state=directory
      with_items:
        - "/home/vagrant/docker"
        - "/home/vagrant/docker/postgres"
        - "/home/vagrant/docker/gitlab"

    # make sure to use the API version that Docker supports. EPEL has Docker
    # 1.6, so use API 1.18
    - name: "docker run postgres"
      docker:
        name: postgres
        image: postgres
        state: started
        volumes:
          - "/home/vagrant/docker/postgres:/var/lib/postgresql/data"
        env:
          POSTGRES_PASSWORD: "{{ postgres_password }}"
        docker_api_version: "1.18"
